-- FiskeDex v28 – flere fangster per art
-- Kjør denne i Supabase → SQL Editor → New query → Run.
-- Den sletter ingenting. Den lager en ny fangstlogg og kopierer gamle fangster inn én gang.

create table if not exists public.catch_entries (
  id bigint generated by default as identity primary key,
  species_id text not null references public.species(id) on delete cascade,
  member text not null,
  dato text default '',
  sted text default '',
  lengde text default '',
  vekt text default '',
  kommentar text default '',
  has_photo boolean default false,
  photo_data text,
  photo_thumb text,
  lat double precision,
  lng double precision,
  weather_summary text default '',
  tide_summary text default '',
  reactions jsonb default '{}'::jsonb,
  legacy_key text unique,
  created_at timestamptz default now()
);

-- Trygt dersom dere allerede har opprettet tabellen.
alter table public.catch_entries add column if not exists photo_data text;
alter table public.catch_entries add column if not exists photo_thumb text;
alter table public.catch_entries add column if not exists legacy_key text;
alter table public.catch_entries add column if not exists weather_summary text default '';
alter table public.catch_entries add column if not exists tide_summary text default '';
alter table public.catch_entries add column if not exists reactions jsonb default '{}'::jsonb;
alter table public.catch_entries add column if not exists lat double precision;
alter table public.catch_entries add column if not exists lng double precision;
alter table public.catch_entries add column if not exists created_at timestamptz default now();

-- Sikrer unik migreringsnøkkel selv dersom tabellen ble startet manuelt.
create unique index if not exists catch_entries_legacy_key_unique
  on public.catch_entries(legacy_key) where legacy_key is not null;

-- Kopier hver gammel fangst til fangstloggen. Bildet følger med når det finnes.
-- NOT EXISTS gjør at SQL-en er trygg å kjøre flere ganger.
insert into public.catch_entries (
  species_id, member, dato, sted, lengde, vekt, kommentar, has_photo,
  photo_data, photo_thumb, lat, lng, weather_summary, tide_summary, reactions,
  legacy_key, created_at
)
select
  c.species_id, c.member, coalesce(c.dato,''), coalesce(c.sted,''),
  coalesce(c.lengde,''), coalesce(c.vekt,''), coalesce(c.kommentar,''),
  coalesce(c.has_photo,false) or p.data is not null,
  p.data, coalesce(p.thumb,p.data), c.lat, c.lng,
  coalesce(c.weather_summary,''), coalesce(c.tide_summary,''), coalesce(c.reactions,'{}'::jsonb),
  'legacy:' || c.species_id || ':' || c.member,
  coalesce(c.created_at, now())
from public.catches c
left join public.photos p on p.species_id=c.species_id and p.member=c.member
where not exists (
  select 1 from public.catch_entries e
  where e.legacy_key='legacy:' || c.species_id || ':' || c.member
);

alter table public.catch_entries enable row level security;
grant usage on schema public to anon, authenticated;
grant select on public.catch_entries to anon, authenticated;
grant insert, update, delete on public.catch_entries to authenticated;
grant usage, select on sequence public.catch_entries_id_seq to authenticated;

drop policy if exists "fiskedex_read_catch_entries" on public.catch_entries;
drop policy if exists "fiskedex_insert_catch_entries" on public.catch_entries;
drop policy if exists "fiskedex_update_catch_entries" on public.catch_entries;
drop policy if exists "fiskedex_delete_catch_entries" on public.catch_entries;

create policy "fiskedex_read_catch_entries" on public.catch_entries
  for select to anon, authenticated using (true);
create policy "fiskedex_insert_catch_entries" on public.catch_entries
  for insert to authenticated with check (member <> '*');
create policy "fiskedex_update_catch_entries" on public.catch_entries
  for update to authenticated using (member <> '*') with check (member <> '*');
create policy "fiskedex_delete_catch_entries" on public.catch_entries
  for delete to authenticated using (true);

do $$ begin
  alter publication supabase_realtime add table public.catch_entries;
exception when duplicate_object then null;
end $$;
